[versions]
androidx-activity = "1.12.3"
androidx-annotaion = "1.9.1"
androidx-datastore = "1.2.0"
androidx-lifecycle-compose = "2.10.0"
androidx-paging = "3.4.0"
androidx-splashscreen = "1.2.0"
android-secrets = "2.0.1"

buildKonfig = "0.17.1"

coil = "3.3.0"
compose-placeholder = "1.0.12"

decompose = "3.4.0"
declarative-snackbar = "0.2.0"
detekt = "1.23.8"
detekt-ruleset-compiler = "0.0.4"
detekt-ruleset-compose = "0.5.6"
detekt-ruleset-decompose = "1.0.1"

essenty = "2.5.0"

gradle-plugin-android = "9.0.0"

jetbrains-compose = "1.10.0"
jetbrains-compose-material3 = "1.9.0"
jetbrains-viewmodel = "2.9.6"

kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
kotlinx-serialization = "1.10.0"
kermit = "2.0.8"
ktor = "3.4.0"
ksp = "2.3.5"

metro = "0.10.2"
moko-permissions = "0.20.1"

room = "2.8.4"

sqlite = "2.6.2"
settings = "1.3.0"
supabase = "3.3.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-annotaion = { module = "androidx.annotation:annotation", version.ref = "androidx-annotaion" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle-compose" }
androidx-paging = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splashscreen" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
compose-placeholder = { module = "com.eygraber:compose-placeholder", version.ref = "compose-placeholder" }

decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions-android = { module = "com.arkivanov.decompose:extensions-android", version.ref = "decompose" }
decompose-extensions-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
decompose-extensions-compose-experimental = { module = "com.arkivanov.decompose:extensions-compose-experimental", version.ref = "decompose" }
declarative-snackbar-compose = { module = "io.github.ajiekcx:declarative-snackbar-compose", version.ref = "declarative-snackbar" }
detekt-ruleset-compiler = { module = "com.braisgabin.detekt:kotlin-compiler-wrapper", version.ref = "detekt-ruleset-compiler" }
detekt-ruleset-ktlint = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-ruleset-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detekt-ruleset-compose" }
detekt-ruleset-decompose = { module = "uk.kulikov.detekt.decompose:decompose-detekt-rules", version.ref = "detekt-ruleset-decompose" }

essenty-state-keeper = { module = "com.arkivanov.essenty:state-keeper", version.ref = "essenty" }
essenty-parcelize = { module = "com.arkivanov.parcelize.darwin:runtime", version.ref = "essenty" }
essenty-lifecycle = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }
essenty-lifecycle-coroutines = { module = "com.arkivanov.essenty:lifecycle-coroutines", version.ref = "essenty" }

gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "gradle-plugin-android" }
gradlePlugin-buildKonfig = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "buildKonfig" }
gradlePlugin-buildKonfig-compiler = { module = "com.codingfeline.buildkonfig:buildkonfig-compiler", version.ref = "buildKonfig" }
gradlePlugin-compose = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
gradlePlugin-metro = { module = "dev.zacsweers.metro:dev.zacsweers.metro.gradle.plugin", version.ref = "metro" }
gradlePlugin-room = { module = "androidx.room:room-gradle-plugin", version.ref = "room" }

jetbrains-compose-animation = { module = "org.jetbrains.compose.animation:animation", version.ref = "jetbrains-compose" }
jetbrains-compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "jetbrains-compose" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "jetbrains-compose" }
jetbrains-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "jetbrains-compose-material3" }
jetbrains-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "jetbrains-compose" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "jetbrains-compose" }

ktor-engine-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

metro-android = { module = "dev.zacsweers.metro:metrox-android", version.ref = "metro" }
metro-viewmodel = { module = "dev.zacsweers.metro:metrox-viewmodel", version.ref = "metro" }
moko-permissions-location = { module = "dev.icerock.moko:permissions-location", version.ref = "moko-permissions" }
moko-permissions-compose = { module = "dev.icerock.moko:permissions-compose", version.ref = "moko-permissions" }

sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "settings" }
settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "settings" }
settings-datastore = { module = "com.russhwolf:multiplatform-settings-datastore", version.ref = "settings" }
supabase-bom = { module = "io.github.jan-tennert.supabase:bom", version.ref = "supabase"  }
supabase-auth = { module = "io.github.jan-tennert.supabase:auth-kt" }
supabase-coil = { module = "io.github.jan-tennert.supabase:coil3-integration" }
supabase-postgrest = { module = "io.github.jan-tennert.supabase:postgrest-kt" }
supabase-storage = { module = "io.github.jan-tennert.supabase:storage-kt" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle-plugin-android" }
android-library = { id = "com.android.library", version.ref = "gradle-plugin-android" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "gradle-plugin-android" }
android-test = { id = "com.android.test", version.ref = "gradle-plugin-android" }
android-secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "android-secrets" }

buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }

detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

metro = { id = "dev.zacsweers.metro", version.ref = "metro" }

room = { id = "androidx.room", version.ref = "room" }

kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# Plugins defined by this project
voyager-lint = { id = "voyager.lint", version = "unspecified" }
voyager-room = { id = "voyager.room", version = "unspecified" }
voyager-kotlin-serialization = { id = "voyager.kotlin.serialization", version = "unspecified" }
voyager-library-multiplatform = { id = "voyager.library.multiplatform", version = "unspecified" }
voyager-library-multiplatform-compose = { id = "voyager.library.multiplatform.compose", version = "unspecified" }
voyager-coil = { id = "voyager.coil", version = "unspecified" }
voyager-application = { id = "voyager.application", version = "unspecified" }
voyager-application-multiplatform = { id = "voyager.application.multiplatform", version = "unspecified" }
voyager-secrets = { id = "voyager.secrets", version = "unspecified" }
voyager-decompose = { id = "voyager.decompose", version = "unspecified" }
voyager-feature-impl = { id = "voyager.feature.impl", version = "unspecified" }
voyager-compose-resources = { id = "voyager.compose.resources", version = "unspecified" }
voyager-ktor = { id = "voyager.ktor", version = "unspecified" }