name: Check labels from linked issues

on:
  pull_request:
    # TODO
#    types: [ opened ]

jobs:
  copy-labels:
    runs-on: ubuntu-latest
    name: Copy labels from linked issues

    permissions:
      issues: read
      pull-requests: write

    steps:
      - name: copy-labels
        uses: michalvankodev/copy-issue-labels@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}